config/routes.rb
Rails.application.routes.draw do
  root to: 'languages#index'
  resources :languages, only: [ :index, :show ] do
    resources :reviews, only: [ :create ]
  end
  resources :reviews, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :reviews 
  validates :name, :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :language, touch: true # Let the parent know something changed! 
  validates :content, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  def index
    @languages = Language.all
  end

  def show
    @language = Language.find(params[:id])
    @review = Review.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @language = Language.find(params[:language_id])
    @review.language = @language
    if @review.save
      redirect_to @review.language
    else
      render 'languages/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @review.language
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/_language.html.erb
<h4><%= link_to language.name, language %></h4>
<p><%= language.description %></p>

app/views/languages/index.html.erb
<div class="container">
  <% cache @languages do %>
    <h1>Languages used at Le Wagon</h1>
    <%= render @languages %>
  <% end %>
</div>

app/views/languages/show.html.erb
<div class="container">
  <p style="margin-top: 30px;"><%= link_to "Back", languages_path, class: "btn btn-primary" %></p>

  <% cache @language do %>
    <h1><%= @language.name %></h1>
    <p><%= @language.description %></p>

    <h4>Reviews:</h4>
    <ul>
      <%= render(@language.reviews, cached: true) || "No reviews yet... Add your own!" %>
    </ul>
  <% end %>

  <%= simple_form_for [@language, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/_review.html.erb
<% cache review do %>
<li>
  <%= review.content %>
  <%= link_to "Delete", review, method: :delete, class: "btn btn-sm btn-danger" %>
</li>
<% end %>